### ISSUE TITLE
DataLayer

### ISSUE THREAD

**Issue by JasperH8g** [kraihn/cordova-plugin-tag-manager#11]
I need to use this approach: https://developers.google.com/tag-manager/devguide#datalayer. Is this possible with this plugin? 

And somewhat related: Why can't we just use the regular implementation of GTM? Why would we need this plugin at all?

**Comment by kraihn** [comment]
No, datalayer isn't supported. The project this was developed for simply didn't need it.

I was experiencing issues with GTM not working due to using cookies, which don't work on Cordova. Because of that, this plugin was developed.

**Comment by DeonKuhn** [comment]
@Jpunt Trying to implement a similar solution with Cordova using dataLayer to track ecommerce via GTM, but found that it does not fire from the phone but does from the web. Did you manage to get the regular implementation working?

**Comment by kraihn** [comment]
I have no idea why I said datalayer isn't supported. Sorry about that. The entire plugin is based on pushing to the datalayer.

For example, pageview tracking.

```
dataLayer.push(DataLayer.mapOf("event", "content-view", "content-name", args.get(0)));
```

**Comment by kraihn** [comment]
@Jpunt and @DeonKuhn, I've added a Wiki page with a list of Macros, Rules and Tags that this plugin requires to manually be setup in GTM in order to allow for pageview and event tracking. Does this help you? There is no support for direct Data Layer access at this time.

**Comment by JasperH8g** [comment]
@kraihn I'm not sure I follow. When I install the plugin and run the init-example, no `dataLayer` array becomes available, either on the `window` or the returned `TagManager`. And even when I create it myself and push objects to that, no XHR's are fired to GTM.

Quick aside: what do you mean with `DataLayer.mapOf`? Normal dataLayer-usage works with plain old js-objects.

**Comment by kraihn** [comment]
I think I'm starting to see the misunderstanding. This plugin works with GTM in the same way that a native mobile application would. The data layer doesn't exist in the WebView where your JavaScript is running. It only exists within the context of the native mobile application code in the plugin. If you look at the source code for this plugin in the Android version, you'll see the DataLayer.mapOf that I was talking about.

The data layer is never exposed to JavaScript, so you can't interact with it directly. The TagManager object in JS isn't supposed to return a data layer, but provide you an interface to the data layer.

**Comment by JasperH8g** [comment]
That doesn't make a lot of sense to me, because in Cordova you're working from the webview all the time. How can we validate that the dataLayer is correct if we can't see it? Anyway, I've got it working without the plugin, thanks anyway.

**Comment by JasperH8g** [comment]
I've received a couple of emails asking me about how I've used standard GTM instead of the plugin. This issue seems to be a better place than answering all emails independently. 

GTM can work without cookies as long as you can keep track of a property that is unique to an user. In my case I generate a UUID and store it in localStorage, as long as it isn't in their already. I send this along with the dataLayer and GTM uses this to identify the user. I'm not familiar with GTM itself, so I can't help you with that. Good luck!
