### ISSUE TITLE
No network calls to GTM

### ISSUE THREAD

**Issue by wrousseau** [kraihn/cordova-plugin-tag-manager#13]
Hi there,

Thanks for the plugin, I'm however having troubles getting data to GTM. `init` works fine, so does `trackPage`. However, `dispatch` does not seem to do much as I'm not getting any data on GA and when debugging the application, I see no network call to GA or GTM.

I know that my setup is correct as I have it working with the web version of the application which does not require cordova, and GA is receiving data fine with it.

If you have any idea of what could be going wrong, I'd really appreciate it,

Cheers

**Comment by kraihn** [comment]
Hi @wrousseau, please provide some more information so I can better assist.
- Are you using the same GTM tracking Id for the web and mobile app?
- Have you gone through the GTM setup instructions listed in the Wiki?
- Are you primarily running against iOS or Android?

**Comment by wrousseau** [comment]
Hi @kraihn ! Thanks for answering :)

I was indeed using the same GTM tracking Id which is for a web application. I believe there was a breaking change with the latest version of GTM as it seems that when trying to fetch the container, we get a 403 error (based on Xcode's console log), probably because it is not a mobile application container. 

I did go through the instructions listed in the Wiki but you'll notice that for a mobile container, we cannot track page views but screen views (or app views, I am unsure because there is absolutely no documentation on Google regarding how to setup the newest GTM with Universal Analytics).

I have tested with another container which is for a mobile application, and I do not get the 403 error anymore but I still cannot get my events on GA, probably because my GTM configuration is wrong...

**Comment by kraihn** [comment]
The discrepancy between page views and screen views shouldn't matter. We use the same data layer variables for web and mobile, both in production. 

Now that you have the mobile container setup, I agree, it should just be tweaking the GTM configurations. I just updated the Wiki to reflect the term changes in GTM V2.

**Comment by wrousseau** [comment]
I agree. However the issue is that we now are required to use a mobile container on GTM (which is now I believe at v4 and not v2) because we get a 403 error when trying to fetch it otherwise.

Mobile containers do not allow using the tag you defined in the wiki which corresponds to a page view.

**Comment by kraihn** [comment]
The only part of GTM that is up to V4 is the native mobile libraries, specifically Android (iOS is still V3). The V2 I was speaking about is basically the GTM API version. Not related to the native libraries. The native libraries used by this plugin are both at V3. Current iOS and Legacy Android. The reason for legacy Android is because V4 requires Google Play Services, which should not be a requirement to everyone.

Mobile containers do allow you to use the custom tags define in the Wiki. Those are the same values I currently use in production.

If you switch the page views to app views, you should be in the clear.

**Comment by kraihn** [comment]
@wrousseau, another team was able to get this working yesterday. If you're interested in following the discussion it took place in issue #14.

**Comment by joey91133** [comment]
I rewrite this plugin with android sdk v4 and use freamwork com.google.android.gms:play-services-analytics:+ to replace lib.
Because I need to use cordova-plugin-admobpro to put ad.
and two plugin use different GA.
Can you check the code after my pull request??

**Comment by wrousseau** [comment]
@kraihn Some follow up about this ! It does work and it seems that we can use a single Tag Manager container for both Android and iOS versions (although it might not be the best choice). Thanks a lot for your help
