### ISSUE TITLE
I can't post anything to GTM server

### ISSUE THREAD

**Issue by dannyyaou** [kraihn/cordova-plugin-tag-manager#14]
Hello: Thanks for making this for us.
But when I used this plugin, and did tagManager.dispatch();
I can get the callback of success;
But my GA can't get anything because there's no post to GTM server from my app.

By the way, we've changed the native libraries of GTM to the newest libraries, both of two platform.

Thanks a lot!

**Comment by kraihn** [comment]
I'm not able to support a manual update of the GTM libraries.

If you use the existing libraries I have two questions.
1. Have you created a mobile app specific container in GTM?
2. Have you completed all of the GTM container setup instructions as outlined in my Wiki?

**Comment by puusaari** [comment]
Hi,

We also had the problem of not receiving anything to GA, and we found that reason was on tag manager configuration.

We changed these:
appName = {{app name}}
appVersion = {{app version}}

to be these:
appName = {{App Name}}
appVersion = {{App Version Code}}

**Comment by kraihn** [comment]
@puusaari, thank you for the feedback. I'm guessing that's the new GTM default, as opposed to the older variables I'm using.

**Comment by joey91133** [comment]
Hi @kraihn 
We createda a mobile app container in GTM
and completed all setup.
![screenshot-tagmanager google com 2015-08-24 22-30-21](https://cloud.githubusercontent.com/assets/8022316/9442841/85b9ff5c-4ab0-11e5-8f5e-4e3908b9c637.png)
![screenshot-tagmanager google com 2015-08-24 22-31-52](https://cloud.githubusercontent.com/assets/8022316/9442852/8b8a308c-4ab0-11e5-9ff0-2d96639df8d2.png)
![screenshot-tagmanager google com 2015-08-24 22-32-40](https://cloud.githubusercontent.com/assets/8022316/9442855/8eca4a84-4ab0-11e5-9fbf-ea975c9666ae.png)
and set tagManager.trackPage(success,fail,'/index.html')
But still can't see any data on GA

**Comment by kraihn** [comment]
@joey91133, how long have your GA and GTM accounts been setup? I've had issues where I needed to wait 24 hours before being able to use a GA account or a GTM container.

**Comment by joey91133** [comment]
@kraihn ,We Create GA and GTM 1 week ago.

**Comment by kraihn** [comment]
@joey91133 are you using the newer libraries as well? I haven't worked with those yet as they require Google Play Services to be included.

**Comment by joey91133** [comment]
@kraihn no,I use your plugin libraries.
and do this
var tagManager = cordova.require('com.jareddickson.cordova.tag-manager.TagManager');
tagManager.init(null, null, GTM-XXXXX, 30);
tagManager.trackPage(null, null, 'index.html');
and xcode log is
![bb](https://cloud.githubusercontent.com/assets/8022316/9443841/fca4f52c-4ab5-11e5-9038-5fe8dfece358.png)

**Comment by kraihn** [comment]
@joey91133, looking at the screenshot of your Pageviews Tag, I can see that you haven't assigned the "screenName" variable to be the one sent by my plugin.

screenName = {{angulartics page path}}

**Comment by joey91133** [comment]
@kraihn If i set
screenName = {{angulartics page path}}
will be error on publish
![cc](https://cloud.githubusercontent.com/assets/8022316/9444316/73bb56f4-4ab8-11e5-8e04-4dc318dcb2c0.png)
I only can set 
screenName = {{page path}}

**Comment by kraihn** [comment]
@joey91133 Ah, yes. {{page path} is correct. I forgot that I changed that piece in the docs. That should be what you need.

**Comment by joey91133** [comment]
and xcode log is 
![dd](https://cloud.githubusercontent.com/assets/8022316/9444503/ca94daf8-4ab9-11e5-85cd-9df173ade219.png)
Do i need to wait 24hr?

**Comment by kraihn** [comment]
Does firing the dispatch command manually work?

**Comment by joey91133** [comment]
my code is
var tagManager = cordova.require('com.jareddickson.cordova.tag-manager.TagManager');
tagManager.init(null, null, trackingId, 10);
tagManager.trackPage(function(){console.log('success track')}, function(error){console.log(error)}, url);
tagManager.dispatch(function(){console.log('success dispatch')}, function(error){console.log(error)});
and xcode log is same
console.log result is 
![ee](https://cloud.githubusercontent.com/assets/8022316/9445068/c1a59858-4abc-11e5-8593-1d011004ea65.png)

so Can I see in GA now???

**Comment by kraihn** [comment]
It should be available in the realtime view of GA now as far as I can tell.

**Comment by joey91133** [comment]
I can't see any active user on GA realtime.
Do I have another way to check this??

**Comment by kraihn** [comment]
You can try working with the GTM debug tools, but I haven't had great success with them.

I've also experienced issues with firewalls blocking connections to GTM in the past.

**Comment by joey91133** [comment]
How can i check if firewalls blocking??

**Comment by kraihn** [comment]
I'm sorry, but I can't help you with a firewall issue because it has nothing to do with this code or GA/GTM. It's probably not the issue you're facing. I only mentioned it as a possibility.

I don't believe I can do anything else for you at this time. Because your Xcode logs look good, I don't believe this to be a code issue. It's most likely that there is still something misconfigured in your GTM setup.

**Comment by joey91133** [comment]
OK
Thanks for your help.
I think is time delay of GA.
I will check later.

**Comment by puusaari** [comment]
Hi,

How did you set up variables on Tag Manager? We have them as in this image:

![variables](https://cloud.githubusercontent.com/assets/13781584/9450049/0a853bcc-4aaf-11e5-81a3-e64d9e9c3df2.PNG)

**Comment by dannyyaou** [comment]
I am co-worker with @joey91133, thanks for your help, it works when we wake up this morning !
![2015-08-25 10 30 15](https://cloud.githubusercontent.com/assets/8759099/9457380/672a02da-4b14-11e5-89d7-3936baf0fe38.png)
