### ISSUE TITLE
Example to use tag manager

### ISSUE THREAD

**Issue by mitsuishihidemi** [kraihn/cordova-plugin-tag-manager#2]
Hi, 

There is a example about how use this plugin?

Thanks,

Érica

**Comment by kraihn** [comment]
I put together some docs for the README. Is this helpful?

[README](../blob/ef41bf3d46369418daef0865e13712e998dfc1df/README.md)

**Comment by mitsuishihidemi** [comment]
Yes,

Thank you :)
