### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by ema1argentina** [kraihn/cordova-plugin-tag-manager#22]
Hi kraihn,

I've tried to use your plugin to send the statistics to google analytics using GTM, but it doesn't seem to work. I can't see any statistic in Google Analytics.
I have created all the variables/triggers/tags that you described in the wiki page.
I am using cordova -version=4.2.0.

Could be the error the cordova version?
Does your plugin work with GTM v2?

Is there any workaround I could do?

Thanks in advance.
Best Regards,
Emanuel

**Comment by kraihn** [comment]
It normally takes 24 hours for a new account to start receiving analytics information. How long ago did you setup your Google Analytics tracking number?

**Comment by kraihn** [comment]
Yes, the plugin does work with GTM v2.

**Comment by pietrorobbi** [comment]
Hi,
i've the same problem, in my analytics i don't show the statistics.
I've setup my analitycs one week ago.

Can you check my log if you find somthing wrong?

W/GoogleTagManager: No asset file: tagmanager/GTM-XXXXXXXX found.
W/GoogleTagManager: No asset file: tagmanager/GTM-XXXXXXXX.json found (or errors reading it).
W/GoogleTagManager: No default container found; creating an empty container.
W/PluginManager: THREAD WARNING: exec() call to TagManager.initGTM blocked the main thread for 72ms. Plugin should use CordovaInterface.getThreadPool().
I/chromium: [INFO:CONSOLE(173)] "TagManager - success: initGTM - id = GTM-XXXXXXXX; interval = 30 seconds"
I/chromium: [INFO:CONSOLE(173)] "TagManager - success: trackPage - url = /start"
I/chromium: [INFO:CONSOLE(173)] "TagManager - success: trackEvent - category = btn; action = click; label = calendar; value = -1"

**Comment by kraihn** [comment]
Are you getting the message below? The container needs to be pulled from the web into your application. Outside of that, there isn't a lot I can do to assist. There are way too many moving pieces outside of this plugin for me to track it down.

```
GoogleTagManager verbose: Load resource from network finished
```

**Comment by ema1argentina** [comment]
Finally I was missing the wiki configuration.
The plugin works excellent.

Thanks!
Emanuel
