### ISSUE TITLE
Deprecated cordova method on iOS

### ISSUE THREAD

**Issue by edriang** [kraihn/cordova-plugin-tag-manager#24]
For anyone having this error: Plugins/com.jareddickson.cordova.tag-manager/CDVTagManager.m:145:42: No visible @interface for 'CDVPluginResult' declares the selector 'toSuccessCallbackString:'

Must modify tagmanager plugin, class CDVTagManager.m
        replace:     [self writeJavascript:[commandResult toErrorCallbackString:callbackID]];
        with:          [self.commandDelegate sendPluginResult:commandResult callbackId:callbackID];
        in methods:     successWithMessage y failWithMessage

**Comment by kraihn** [comment]
This has now been resolved by PR #32 

See v1.0.1 on NPM
