### ISSUE TITLE
Error when building app

### ISSUE THREAD

**Issue by raphaelgodoi** [kraihn/cordova-plugin-tag-manager#31]
I had this two errors when I build:

error: no visible @interface for 'CDVPluginResult' declares the selector 'toSuccessCallbackString:'
    [self writeJavascript:[commandResult toSuccessCallbackString:callbackID]];

error: no visible @interface for 'CDVPluginResult' declares the selector 'toErrorCallbackString:'
    [self writeJavascript:[commandResult toErrorCallbackString:callbackID]];

**Comment by kraihn** [comment]
Resolved by PR #32
