### ISSUE TITLE
Cannot find plugin.xml

### ISSUE THREAD

**Issue by robmpreston** [kraihn/cordova-plugin-tag-manager#36]
Fetching plugin "com.jareddickson.cordova.tag-manager" via npm
Error: Cannot find plugin.xml for plugin "package". Please try adding it again.

**Comment by yoandro** [comment]
You should be able to solve this by adding the plugin directly from GitHub, this is the command

cordova plugin add https://github.com/kraihn/cordova-plugin-tag-manager.git

**Comment by robmpreston** [comment]
Meant to close it :D
