### ISSUE TITLE
Getting Error on install : Cannot find plugin.xml for plugin "package"

### ISSUE THREAD

**Issue by HollyPony** [kraihn/cordova-plugin-tag-manager#38]
Hi,

Using the README.md command I'm getting this :

```
-> cordova plugin add com.jareddickson.cordova.tag-manager
Fetching plugin "com.jareddickson.cordova.tag-manager@~1.0.1" via npm
Error: Cannot find plugin.xml for plugin "package". Please try adding it again.
```

**System:**
Debian
node -v ● v6.8.0
npm -v ● 3.10.8
cordova -v ● 6.4.0

EDIT: `cordova plugin add cordova-plugin-tag-manager` Works ;)

**Comment by osasereweb** [comment]
Cannot find plugin.xml for plugin "cordova-plugin-admobpro". Please try adding it again.

**Comment by osasereweb** [comment]
How do i resolve this issue?
