### ISSUE TITLE
How to debug the track event

### ISSUE THREAD

**Issue by mitsuishihidemi** [kraihn/cordova-plugin-tag-manager#4]
Hi, 

How to debug track events? I was using Charles and inspect devices of chrome.

But, it isn't sending any request to google analytics. 

This is my code:

``` javascript

var initWebView = function(containerId) {      
      analytics = $window.plugins && $window.plugins.TagManager;
      if (analytics) {
        analytics.init(
          function callSuccess() {
            console.log('SUCCESS');
          },
          function callError(error) {
            console.error('ERROR', error)
          }
          , containerId, 30);
      }
    }; 

...

var pushWebView = function(data) {
      data.domain = $scope.getCurrentDomain();      
      if (analytics) {
        analytics.trackEvent(
          function callSuccess() {
            console.log('SUCCESS AGAIN');
          },
          function callError(error) {
            console.error('ERROR AGAIN', error);
          },
          data.event, data.event, 'data', data);
      }
    };

```

Thanks

**Comment by kraihn** [comment]
Is success being called? How long ago did you create your Tag Manager and Analytics accounts? I've had it take 24 hours before being able to see the realtime analytics.

It's also a manual step to setup the mappings from Tag Manager to Analytics. They should be listed in the Angulartics README of their GitHub repo.

**Comment by kraihn** [comment]
@mitsuishihidemi, have you had any success yet, or are you able to provide more information?

**Comment by mitsuishihidemi** [comment]
Hi @kraihn, thanks for attention, but the task which i was working is stopped. So, I didn't finish it. But when I resume it, I will give you a feedback. ;)
