### ISSUE TITLE
Network Request Whitelist vulnerability?

### ISSUE THREAD

**Issue by BobAchgill** [kraihn/cordova-plugin-tag-manager#40]
I am wondering if there is another way to allow GTM to do its work using the cordova-plugin-tag-manager plugin without having to have this in my config.xml??  When I take it out GTM stops working...

```
<!-- Don't block any requests -->
<access origin="*" />
```

I tried just having this instead but it did not allow GTM to function.

```
	    <access origin="https://www.googletagmanager.com/*" />
	    <allow-intent href="https://www.googletagmanager.com/*" />
```

Isn't it a security risk to use???  
`<access origin="*" />`

**Comment by kraihn** [comment]
Unfortunately this is out of the scope of this plugin and my work. Since I don't manage the domains used by GTM, or know what all of them are, I can't make this modification myself. If you're able to watch your network traffic and see all of the URLs being used, I would love to be able to post those as a recommendation for others.

**Comment by BobAchgill** [comment]
It took me a long time to realize why i was not getting your plugin to work.  It would be helpful that you say somewhere in the setup documentating that the config.xml has to have  that whitelist line in it.

All Cordova doc strongly recommends not using that line so i had removed it not knowing it was a prerequisite for the GTM plugin.

Thanks a million for writing the plugin!

Bob Achgill
________________________________

**Comment by BobAchgill** [comment]
Kraihn,

Do you see these comments once the issue is closed or do I need to start another issue stating the recommendation to modify the setup instructions to list  

`<access origin="*" /> `

be added as a prerequisite?
