### ISSUE TITLE
new TagManager();

### ISSUE THREAD

**Issue by artemkhalygov** [kraihn/cordova-plugin-tag-manager#5]
new TagManager(); doesn't work, what do i do wrong?

**Comment by kraihn** [comment]
Please provide more information so I'm better able to help. An example of how you're using the code would be a great start.
- What error are you getting?
- Are you using this with Cordova/PhoneGap?
- Is `window.plugins.TagManager` defined?
- Are you integrating with AngularJS, or something else?

My primary usage of the plugin is with AngularJS using the analytics module called Angulartics. https://github.com/luisfarzati/angulartics/commit/d7b595a849f48539b940b92a3ca05d30c978e338#diff-90dcce577627fc82458cec4a1efd79b6

**Comment by artemkhalygov** [comment]
I'm getting this error;

new TagManager()
ReferenceError: TagManager is not defined

It's work for me only when i use this code:

var tagManager = cordova.require('com.jareddickson.cordova.tag-manager.TagManager');

But i think it's not right.

I'm using Cordova and i don't integrate it with AngularJS.

Thanks for your answer and sorry for my English

**Comment by jonystorm** [comment]
How do you define window.plugins.TagManager ?

**Comment by kraihn** [comment]
@artemkhalygov, I'm unfamiliar with how you're trying to add plugins to a Cordova/PhoneGap project.

@jonystorm, I don't define window.plugins.TagManager, Cordova sets it all up for me.

The steps below are how I create a Cordova project with a working instance of the TagManager plugin.

```
cordova create tag-manager-test && cd $_
cordova platform add ios
cordova plugin add com.jareddickson.cordova.tag-manager
cordova build ios && cordova run ios
```

Once I have the mobile app running, I can use the Safari debug tools to see that the plugin has been setup, and can then begin to initialize and send events.

**Comment by jonystorm** [comment]
Hi @kraihn , thanks for your prompt answer. I followed your steps to install and run the plugin, and got to the same problem as @artemkhalygov . I tried what he suggested and worked for me, at least, I stopped getting the "not defined" error and everything seemed to be working, the "trackEvent" and "trackPage" callbacks were executed correctly. But for some reason I'm not getting any answer on the GTM site side. I have added GA to test and it doesn't records any activity.

I'm not using AngularJS, I installed the plugin via cordova cli, and I'm testing it on Android.

Any suggestion is welcome.
Thanks in advance.

Br,
Jonatan

**Comment by artemkhalygov** [comment]
@jonystorm I fixed this by this code: 

``` javascript
        var tagManager = cordova.require('com.jareddickson.cordova.tag-manager.TagManager'),
        trackingId = window.device.platform === 'Android' ? 'Your Android Code' : 'Ios Code',
        intervalPeriod = 30;

        var success = function(callback) {
          console.log(callback);
        };
        var error = function(error) {
          console.log(error);
        };

        // Initialize Tag Manager
        tagManager.init(success, error, trackingId, intervalPeriod);
```

And it's work.

**Comment by kraihn** [comment]
I'm not sure if something changed when I initially wrote this, but I have updated the docs to include cordova.require. Thank you for helping to solve this issue.
